### ISSUE TITLE
Immediate power off when shairtunes plugin stops playing

### ISSUE THREAD

**Issue by adamcstephens** [jasonholtzapple/PowerSave#1]
Hi, thanks for this plugin. It's an important part of my setup to ensure my stereo is powered off when not playing.

Unfortunately, when using the Shairtunes2 plugin the power of delay is not honored. Once the device sending the Airplay stops for any reason the player immediately powers off.

Do you have any ideas on why this could be and if it's feasible to fix?

**Comment by sspiff** [comment]
@adamcstephens, were you able to resolve this?  I am experiencing the same issue.  Thanks!

**Comment by adamcstephens** [comment]
No I never have. I only closed the issue after no response in a year.
